# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-02 16:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20181102_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='user_survey_topics', to=settings.AUTH_USER_MODEL),
        ),
    ]
